"""exp_targets.py - auto-generated by extract_exp_targets.py.

Experimental summary targets used by tof_calibrate.py. Re-run
extract_exp_targets.py whenever the processed data changes.
"""

EXP_TARGETS_02 = {
    'fl_initial':       {},
    'snap_time_min':    {},
    'peak_neg_bias_cm': {10: -0.014, 20: 0.103, 30: -0.147, 40: -0.034, 50: -0.027, 60: -0.049},
}

EXP_TARGETS_08 = {
    'fl_initial':       {40: 0.493, 50: 0.461, 60: 0.961},
    'snap_time_min':    {40: 0.75, 50: 1.75, 60: 3.25},
    'peak_neg_bias_cm': {10: 0.071, 20: -1.748, 30: -2.082, 40: -0.576, 50: -0.046, 60: 0.032},
}
